/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soedomoto_vrp_solver_CoESVRPJNI */

#ifndef _Included_com_soedomoto_vrp_solver_CoESVRPJNI
#define _Included_com_soedomoto_vrp_solver_CoESVRPJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soedomoto_vrp_solver_CoESVRPJNI
 * Method:    setVehicles
 * Signature: (I[F[F[F[I)V
 */
JNIEXPORT void JNICALL Java_com_soedomoto_vrp_solver_CoESVRPJNI_setVehicles
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray, jfloatArray, jintArray);

/*
 * Class:     com_soedomoto_vrp_solver_CoESVRPJNI
 * Method:    setCustomers
 * Signature: (I[F[F[I)V
 */
JNIEXPORT void JNICALL Java_com_soedomoto_vrp_solver_CoESVRPJNI_setCustomers
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray, jintArray);

/*
 * Class:     com_soedomoto_vrp_solver_CoESVRPJNI
 * Method:    solve
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_soedomoto_vrp_solver_CoESVRPJNI_solve
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
